export const PLANIFICATOR_SHOW_RESET = "PLANIFICATOR_SHOW_RESET";
export const PLANIFICATOR_SHOW_SET_ERROR = "PLANIFICATOR_SHOW_SET_ERROR";
export const PLANIFICATOR_SHOW_SET_RETRIEVED =
  "PLANIFICATOR_SHOW_SET_RETRIEVED";
export const PLANIFICATOR_SHOW_TOGGLE_LOADING =
  "PLANIFICATOR_SHOW_TOGGLE_LOADING";
