export const PLANIFICATOR_CREATE_RESET = "PLANIFICATOR_CREATE_RESET";
export const PLANIFICATOR_CREATE_SET_CREATED =
  "PLANIFICATOR_CREATE_SET_CREATED";
export const PLANIFICATOR_CREATE_SET_ERROR = "PLANIFICATOR_CREATE_SET_ERROR";
export const PLANIFICATOR_CREATE_SET_VIOLATIONS =
  "PLANIFICATOR_CREATE_SET_VIOLATIONS";
export const PLANIFICATOR_CREATE_TOGGLE_LOADING =
  "PLANIFICATOR_CREATE_TOGGLE_LOADING";
