export const SEARCHTHEME_SHOW_RESET = "SEARCHTHEME_SHOW_RESET";
export const SEARCHTHEME_SHOW_SET_ERROR = "SEARCHTHEME_SHOW_SET_ERROR";
export const SEARCHTHEME_SHOW_SET_RETRIEVED = "SEARCHTHEME_SHOW_SET_RETRIEVED";
export const SEARCHTHEME_SHOW_TOGGLE_LOADING =
  "SEARCHTHEME_SHOW_TOGGLE_LOADING";
