export const STOREDVIDEO_CREATE_RESET = "STOREDVIDEO_CREATE_RESET";
export const STOREDVIDEO_CREATE_SET_CREATED = "STOREDVIDEO_CREATE_SET_CREATED";
export const STOREDVIDEO_CREATE_SET_ERROR = "STOREDVIDEO_CREATE_SET_ERROR";
export const STOREDVIDEO_CREATE_SET_VIOLATIONS =
  "STOREDVIDEO_CREATE_SET_VIOLATIONS";
export const STOREDVIDEO_CREATE_TOGGLE_LOADING =
  "STOREDVIDEO_CREATE_TOGGLE_LOADING";
