export const RESET = "STOREDVIDEO_UPDATE_RESET";
export const SET_ERROR = "STOREDVIDEO_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "STOREDVIDEO_UPDATE_SET_RETRIEVED";
export const SET_UPDATED = "STOREDVIDEO_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "STOREDVIDEO_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "STOREDVIDEO_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "STOREDVIDEO_UPDATE_UPDATE_RETRIEVED";
