<?php

namespace App\Shared\Utils;

class CONSTANT
{
    const MS_YT_DOWNLOADER_BASE_URL = "MS_YT_DOWNLOADER_BASE_URL";
    const MS_YT_DOWNLOADER_URI_STORED_VIDEOS_STATUS = "MS_YT_DOWNLOADER_URI_STORED_VIDEOS_STATUS";
    
    const MS_YT_SEARCH_BASE_URL = "MS_YT_SEARCH_BASE_URL";
    const MS_YT_SEARCH_URI_STORED_THEME = "MS_YT_SEARCH_URI_STORED_THEME";
    const MS_YT_SEARCH_URI_FIND_THEME = "MS_YT_SEARCH_URI_FIND_THEME";
}