    version: '3.8'
services:
  youtube_downloader:
    depends_on:
      - mongo
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - .env
      - ../.common-env
    networks:
      - api-network
      - local-mongo

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    networks:
      - local-mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://MONGO_YT_USER:MONGO_YT_PWD@mongo
    networks:
      - local-mongo
networks:
  api-network:
    external:
      name: project_network
  local-mongo:
    driver: bridge
