export const PLANIFICATOR_DELETE_RESET = "PLANIFICATOR_DELETE_RESET";
export const PLANIFICATOR_DELETE_SET_ERROR = "PLANIFICATOR_DELETE_SET_ERROR";
export const PLANIFICATOR_DELETE_SET_DELETED =
  "PLANIFICATOR_DELETE_SET_DELETED";
export const PLANIFICATOR_DELETE_TOGGLE_LOADING =
  "PLANIFICATOR_DELETE_TOGGLE_LOADING";
