export const SEARCHTHEME_CREATE_RESET = "SEARCHTHEME_CREATE_RESET";
export const SEARCHTHEME_CREATE_SET_CREATED = "SEARCHTHEME_CREATE_SET_CREATED";
export const SEARCHTHEME_CREATE_SET_ERROR = "SEARCHTHEME_CREATE_SET_ERROR";
export const SEARCHTHEME_CREATE_SET_VIOLATIONS =
  "SEARCHTHEME_CREATE_SET_VIOLATIONS";
export const SEARCHTHEME_CREATE_TOGGLE_LOADING =
  "SEARCHTHEME_CREATE_TOGGLE_LOADING";
