export const RESET = "SEARCHTHEME_LIST_RESET";
export const SET_ITEMS = "SEARCHTHEME_LIST_SET_ITEMS";
export const SET_ERROR = "SEARCHTHEME_LIST_SET_ERROR";
export const SET_SELECT_ITEMS = "SEARCHTHEME_LIST_SET_SELECT_ITEMS";
export const SET_VIEW = "SEARCHTHEME_LIST_SET_VIEW";
export const TOGGLE_LOADING = "SEARCHTHEME_LIST_TOGGLE_LOADING";
