export const RESET = "STOREDVIDEO_LIST_RESET";
export const SET_ITEMS = "STOREDVIDEO_LIST_SET_ITEMS";
export const SET_ERROR = "STOREDVIDEO_LIST_SET_ERROR";
export const SET_SELECT_ITEMS = "STOREDVIDEO_LIST_SET_SELECT_ITEMS";
export const SET_VIEW = "STOREDVIDEO_LIST_SET_VIEW";
export const TOGGLE_LOADING = "STOREDVIDEO_LIST_TOGGLE_LOADING";
