export const STOREDVIDEO_DELETE_RESET = "STOREDVIDEO_DELETE_RESET";
export const STOREDVIDEO_DELETE_SET_ERROR = "STOREDVIDEO_DELETE_SET_ERROR";
export const STOREDVIDEO_DELETE_SET_DELETED = "STOREDVIDEO_DELETE_SET_DELETED";
export const STOREDVIDEO_DELETE_TOGGLE_LOADING =
  "STOREDVIDEO_DELETE_TOGGLE_LOADING";
