export const RESET = "SEARCHTHEME_UPDATE_RESET";
export const SET_ERROR = "SEARCHTHEME_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "SEARCHTHEME_UPDATE_SET_RETRIEVED";
export const SET_UPDATED = "SEARCHTHEME_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "SEARCHTHEME_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "SEARCHTHEME_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "SEARCHTHEME_UPDATE_UPDATE_RETRIEVED";
