export const AUTH_LOGIN_TOGGLE_LOADING = "AUTH_LOGIN_TOGGLE_LOADING";
export const AUTH_LOGIN_SET_LOGGED = "AUTH_LOGIN_SET_LOGGED";
export const AUTH_LOGIN_SET_VIOLATIONS = "AUTH_LOGIN_SET_VIOLATIONS";
export const AUTH_LOGIN_SET_ERROR = "AUTH_LOGIN_SET_ERROR";
export const AUTH_LOGIN_RESET = "AUTH_LOGIN_RESET";
