export const RESET = "PLANIFICATOR_UPDATE_RESET";
export const SET_ERROR = "PLANIFICATOR_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "PLANIFICATOR_UPDATE_SET_RETRIEVED";
export const SET_UPDATED = "PLANIFICATOR_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "PLANIFICATOR_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "PLANIFICATOR_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "PLANIFICATOR_UPDATE_UPDATE_RETRIEVED";
