export const STOREDVIDEO_SHOW_RESET = "STOREDVIDEO_SHOW_RESET";
export const STOREDVIDEO_SHOW_SET_ERROR = "STOREDVIDEO_SHOW_SET_ERROR";
export const STOREDVIDEO_SHOW_SET_RETRIEVED = "STOREDVIDEO_SHOW_SET_RETRIEVED";
export const STOREDVIDEO_SHOW_TOGGLE_LOADING =
  "STOREDVIDEO_SHOW_TOGGLE_LOADING";
