export const RESET = "PLANIFICATOR_LIST_RESET";
export const SET_ITEMS = "PLANIFICATOR_LIST_SET_ITEMS";
export const SET_ERROR = "PLANIFICATOR_LIST_SET_ERROR";
export const SET_SELECT_ITEMS = "PLANIFICATOR_LIST_SET_SELECT_ITEMS";
export const SET_VIEW = "PLANIFICATOR_LIST_SET_VIEW";
export const TOGGLE_LOADING = "PLANIFICATOR_LIST_TOGGLE_LOADING";
