export const SEARCHTHEME_DELETE_RESET = "SEARCHTHEME_DELETE_RESET";
export const SEARCHTHEME_DELETE_SET_ERROR = "SEARCHTHEME_DELETE_SET_ERROR";
export const SEARCHTHEME_DELETE_SET_DELETED = "SEARCHTHEME_DELETE_SET_DELETED";
export const SEARCHTHEME_DELETE_TOGGLE_LOADING =
  "SEARCHTHEME_DELETE_TOGGLE_LOADING";
