version: "3.9"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
  web:
    build:
      context: .
      dockerfile: .Dockerfile
    command: python myAPI/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - api-network
      - local-network

networks:
  api-network:
    name: project_network
  local-network:
    driver: bridge