version: "3.9"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: youtube-search
    networks:
      - api-network
      - py-local-mongo
  web:
    build:
      context: .
      dockerfile: .Dockerfile
    command: python myAPI/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
    - mongodb
    networks:
      - api-network
      - py-local-mongo
networks:
  api-network:
    external:
      name: project_network
  py-local-mongo:
    driver: bridge
